language: php

php:
  - 5.5

before_install:
  - pip install --user codecov

before_script:
  - npm install -g grunt-cli
  - npm install
  - mkdir -p dist/js
  - mkdir -p tests/logs

install:
  - composer self-update
  - composer install --no-interaction

script:
  - phpunit
  - npm test
  - grunt build

after_success:
  - codecov

deploy:
  provider: releases
  api_key: "99cf62656806a7c2c77813330acf5ab2b9606330"
  file: "pulsar.zip"
  skip_cleanup: true
  on:
    tags: true
