language: php

php:
  - 5.5

before_script:
  - npm install -g grunt-cli
  - npm install
  - mkdir -p dist/js

install:
  - composer self-update
  - composer install --no-interaction

script:
  - phpunit
  - npm test
