language: php

php:
  - 5.5

before_script:
  - npm install -g grunt-cli
  - npm install
  - mkdir -p dist/js
  - mkdir -p build/logs

install:
  - composer self-update
  - composer install --no-interaction

script:
  - phpunit
  - npm test

after_success:
  - travis_retry php vendor/bin/coveralls
