language: php

php:
  - 5.5

before_script:
  - npm install -g grunt-cli
  - npm install -S console-browserify
  - npm install

install:
  - composer self-update
  - composer install --no-interaction

script:
  - phpunit
  - npm test
