---
- hosts: all
  tasks:
    - name: install server components
      apt: name={{ item }} state=present update_cache=yes
      become: yes
      with_items:
       - apache2
       - mysql-server
       - php5-mysql
       - php5
       - git

    - name: update php.ini
      become: yes
      template: >
        src=./templates/php.ini.j2
        dest=/etc/php5/apache2/php.ini
        owner=root
        group=root
        mode=0644

    - name: ensure server components are running
      service: name={{ item }} state=started enabled=yes
      with_items:
       - apache2
       - mysql
